#!/usr/bin/env bash
# Script that upgrades Zoom to the latest version

set -e -o pipefail

echo "Exiting Zoom"
if pgrep zoom; then
  pkill zoom;
fi

cd ~/Downloads/

[[ -f zoom_amd64.deb ]] && rm -fr zoom_amd64.deb

echo "Downloading latest Zoom version"
curl -fsSL https://zoom.us/linux/download/pubkey | sudo apt-key add -
curl -sL https://zoom.us/client/latest/zoom_amd64.deb -o zoom_amd64.deb

echo "Uninstalling Zoom"
sudo apt purge -y zoom

echo "Installing latest Zoom"
sudo apt install -y ./zoom_amd64.deb

echo "Starting Zoom"
zoom &

cd -

echo "Done"
